.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "URLSCAN" "" "June 2014" "" "urlscan"
Urlscan is a small program that parses stdin and generates a list of links which can then be browsed through to launch a desired link in the web browser defined by \fB$BROWSER\fR\. It is designed to replace "urlview" and integrate with the "mutt" mailreader to allow you to easily launch a Web browser for URLs contained in email messages\.
.
.SH "Features"
Urlscan parses an email message passed on standard input and scans it for URLs\. It then displays the URLs and their context within the message, and allows you to choose one or more URLs to send to your Web browser\.
.
.P
Relative to urlview, urlscan has the following additional features:
.
.IP "\(bu" 4
Support for emails in quoted\-printable and base64 encodings\. No more stripping out =40D from URLs by hand!
.
.IP "\(bu" 4
The context of each URL is provided along with the URL\. For HTML mails, a crude parser is used to render the HTML into text\.
.
.IP "" 0
.
.SH "Configure for Mutt"
To set up urlscan, install the "urlscan\-git" package (or use setup\.py to install the program)\. Once urlscan is installed, add the following lines to your \.muttrc:
.
.IP "" 4
.
.nf

macro index,pager \ecb "<pipe\-message> urlscan<Enter>" "call urlscan to extract URLs out of a message"
macro attach,compose \ecb "<pipe\-entry> urlscan<Enter>" "call urlscan to extract URLs out of a message"
.
.fi
.
.IP "" 0
.
.P
Once this is done, Control\-b while reading mail in mutt will automatically invoke urlscan on the message\.
.
.P
To choose a particular browser, set the environment variable BROWSER; e\.g\.: \fBexport BROWSER=/usr/bin/epiphany\fR
.
.SH "Known bugs and limitations"
.
.IP "\(bu" 4
Because the Python curses module does not support wide characters (see Debian bug #336861), non\-ASCII characters can cause unpredictable results in urlscan\. This problem will go away if Python and urwid are patched to support wide characters\.
.
.IP "\(bu" 4
Running urlscan sometimes "messes up" the terminal background\. This seems to be an urwid bug, but I haven\'t tracked down just what\'s going on\.
.
.IP "\(bu" 4
Extraction of context from HTML messages leaves something to be desired\. Probably the ideal solution would be to extract context on a word basis rather than on a paragraph basis\.
.
.IP "\(bu" 4
The HTML message handling is a bit kludgy in general\.
.
.IP "\(bu" 4
multipart/alternative sections are handled by descending into all the sub\-parts, rather than just picking one, which may lead to URLs and context appearing twice\.
.
.IP "\(bu" 4
Configurability is more than a little bit lacking\.
.
.IP "" 0
.
.SH "Credits"
.
.IP "\(bu" 4
\fBMaintainer\fR: Scott Hansen \fIfirecat4153@gmail\.com\fR
.
.IP "\(bu" 4
\fBOriginal Author\fR: Daniel Burrows \fIdburrows@debian\.org\fR
.
.IP "" 0

