#!/bin/sh

post_install() {
  echo "
:: Getting Started with Twittor ::

Under /usr/share/twittor-git you will see to python files which are

implant.py - the backdoor to deploy
twittor.py - which is the client

In both files, edit the access token part and add the ones that you previously generated:

CONSUMER_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
CONSUMER_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

ACCESS_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
ACCESS_TOKEN_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

USERNAME = 'XXXXXXXXXXXXXXXXXXXXXXXX'


You're probably going to want to compile implant.py into an executable using Pyinstaller. 

In order to remove the console when compiling with Pyinstaller, the flags --noconsole --onefile will help.
"
}
