rebuild_module_dependencies() {
	EXTRAMODULES='extramodules-3.18-archstrike'
	depmod $(cat /lib/modules/$EXTRAMODULES/version)
}

post_install() {
  rebuild_module_dependencies
	echo '>>> The module r8168 conflicts with r8169. You can blacklist it with:'
	echo '>>>  `echo "blacklist r8169" > /etc/modprobe.d/r8169_blacklist.conf`'
}
post_upgrade() {
	rebuild_module_dependencies
}

post_remove() {
	rebuild_module_dependencies
}
