post_install() {
    EXTRAMODULES='extramodules-3.16-archstrike'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
    echo 'In order to use nvidia module, reboot the system.'
}

post_upgrade() {
    EXTRAMODULES='extramodules-3.14-lts'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}

post_remove() {
    EXTRAMODULES='extramodules-3.14-lts'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}
