#Automatically generated by pip2arch on 2017-11-21

# Maintainer: oneup <oneup40 at gmail dot com>

pkgname=python2-z3-solver
pkgver=4.5.1.0.post2
pkgrel=1
pkgdesc="an efficient SMT solver library"
url="https://github.com/Z3Prover/z3"
depends=('python2' )
makedepends=('python2-distribute' )
license=('CUSTOM')
arch=('any')
source=('https://pypi.python.org/packages/23/40/e2340141ac1b374b3e7cc641c66ade04290676662bc80e1f40281d225b57/z3-solver-4.5.1.0.post2.tar.gz'
        'https://raw.githubusercontent.com/Z3Prover/z3/master/LICENSE.txt')
md5sums=('73cfbdb65c015494ce67cdc6e4504fb0'
         '5f03ad1486a2e4ce71200ce0f9721557')

build() {
    cd $srcdir/z3-solver-4.5.1.0.post2
    python2 setup.py build
}

package() {
    cd $srcdir/z3-solver-4.5.1.0.post2
    python2 setup.py install --root="$pkgdir" --optimize=1 
    install -Dm644 $srcdir/LICENSE.txt "$pkgdir"/usr/share/licenses/$pkgname/LICENSE.txt
}
