post_install() {
  update-desktop-database -q
  udevadm control --reload-rules &> /dev/null

  echo "---------------------------------------------------------
Before using MPLAB X you have to agree with LICENSE:
/usr/share/licenses/microchip-mplabx-bin/LICENSE

To run MPLAB X type 'mplab_ide' in console or just use the 'microchip-mplabx.desktop' desktop file.

To run (IPE) Integrated Programmer Environment (Beta) type 'mplab_ipe' in console or just use the 'microchip-mplab_ipe.desktop' desktop file.
---------------------------------------------------------"
}

post_upgrade() {
  post_install
}

post_remove() {
  update-desktop-database -q
  udevadm control --reload-rules &> /dev/null
}
