#!/usr/bin/env bash

# run to check for packages that don't have a groups array

curr_dir="$(readlink -f "$0")"
curr_dir="${curr_dir%\/*}"
cd "$curr_dir"/.. || exit

while read -r; do
    egrep -q '^\ *groups=' "$REPLY" || {
        pkg="${REPLY%\/*}"
        pkg="${pkg/\.\/}"
        printf '%s\n' "$pkg"
    }
done < <(find . -name 'PKGBUILD')
