#!/usr/bin/env bash

[[ -z "$1" ]] && {
    printf '%s\n' 'Package Check: Run from the base of the repo to find PKGBUILDs matching the regex'
    printf '%s\n' 'USAGE: ./pkg-check "regex match"'
    exit
}

while read -r; do
    [[ -f "$REPLY" ]] || continue
    egrep -q "'$1'" "$REPLY" && sed 's|^\./||;s|/PKGBUILD||' <<< "$REPLY"
done < <(find . -maxdepth 3 -name 'PKGBUILD')

