#!/usr/bin/env bash
PKG="$1"
[[ -z "$PKG" ]] && echo "Please provide a package to search for." && exit 1
DIR=$(find .. -maxdepth 2 -regex ".*$PKG")
[[ -z "$DIR" ]] && echo "Package not found..." && exit 1
eval $(pcregrep -M '^depends=([^)]*)' $DIR/PKGBUILD | sed ':a;N;$!ba;s/\n/ /g' | sed -E 's/[ ]+/ /g')
SPATTERN=$(echo "${depends[@]}" | sed -E 's/ (python2?-)?/|/g' | sed -E 's/python2?-//g'|sed -E 's/(.*)/(python2?-)?\(\1\)/g')
SRESULTS=( $(pacman -Ss "$SPATTERN" | grep -E "[-a-z]/$SPATTERN " | grep -oE '^[^ ]*') )
ASRESULTS=( $( for sres in "${SRESULTS[@]}"; do echo $sres | grep -E "^archstrike(-testing)?/" ;done) )

printf "ArchStrike Dependencies for %s\n" "$PKG"
printf '=%.0s' {1..40}
printf '\n'
for asres in "${ASRESULTS[@]}"; do
    printf "%s\n" "$asres"
done

printf "Reverse Dependencies for %s\n" "$PKG"
printf '=%.0s' {1..40}
printf '\n'
pactree -sr "$PKG"
