#!/usr/bin/env bash
PKG="$1"
[[ -z "$PKG" ]] && echo "Please provide a package to search for." && exit 1
DIR=$(find .. -maxdepth 2 -regex ".*/$PKG")
[[ -z "$DIR" ]] && echo "Package not found..." && exit 1
eval $(pcregrep -M '^depends=([^)]*)' $DIR/PKGBUILD | sed ':a;N;$!ba;s/\n/ /g' | sed -E 's/[ ]+/ /g')
eval $(pcregrep -M '^makedepends=([^)]*)' $DIR/PKGBUILD | sed ':a;N;$!ba;s/\n/ /g' | sed -E 's/[ ]+/ /g')
alldepends=( "${depends[@]}" "${makedepends[@]}" )
SPATTERN=$(echo "${alldepends[@]}" | sed -E 's/ (python2?-)?/|/g' | sed -E 's/python2?-//g'|sed -E 's/(.*)/(python2?-)?\(\1\)/g')
SRESULTS=( $(pacman -Ss "$SPATTERN" | grep -E "[-a-z]/$SPATTERN " | grep -oE '^[^ ]*') )
ASRESULTS=( $( for sres in "${SRESULTS[@]}"; do echo $sres | grep -E "^archstrike(-testing)?/" ;done) )
REVTREE="$(pactree -sr $PKG)"

print_hline() {
  printf "=%.0s" {1..60}
  printf "\n"
}

print_description() {
  print_hline
  printf "Description of %s\n" "$PKG"
  print_hline
  RDEPENDS_COUNT=$(printf "%s\n" "${REVTREE}" | tail -n+2 | wc -l)
  DEPENDS_COUNT=$(printf "%s" "${#ASRESULTS[@]}")
  printf "Location: %s\n" "${DIR//\.\.\//}"
  if [[ ${RDEPENDS_COUNT} == 0 ]] && [[ ${DEPENDS_COUNT} == 0 ]]; then
    printf "Type: STANDALONE\n"
  else
    printf "Type: COMPONENT\n"
  fi
  printf "\n"
}

print_depends() {
  print_hline
  printf "ArchStrike Dependencies for %s\n" "${PKG}"
  print_hline
  for asres in "${ASRESULTS[@]}"; do
    printf "%s\n" "$asres"
  done
  printf "\n"
}

print_rdepends() {
  print_hline
  printf "Reverse Dependencies of %s\n" "${PKG}"
  print_hline
  printf "%s\n" "${REVTREE}"
  printf "\n"
}


print_description
print_depends
print_rdepends
# vim:se ts=2 sw=2 sts=2 et:
